export enum ProjectStatus {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    DELAYED = "DELAYED",
    WAITING = "WAITING",
    REJECTED = "REJECTED"
}